"""
chat_orchestrator.py
====================
Handles conversational AI interactions for the Astrikos framework via Ollama.
"""

import requests

OLLAMA_URL = "http://localhost:11434/api/chat"
SYSTEM_PROMPT = {
    "role": "system",
    "content": "You are Nexus Assistant, an expert AI data scientist helping the user build machine learning pipelines in a drag-and-drop framework. Be concise and helpful."
}

def generate_chat_response(messages: list) -> str:
    """
    Send a list of messages to the local Ollama chat API and return the response.
    
    Parameters
    ----------
    messages : list
        A list of dictionaries containing 'role' and 'content' keys.
        
    Returns
    -------
    str
        The text response generated by the assistant.
    """
    # Create a copy of the list and prepend the system prompt
    payload_messages = [SYSTEM_PROMPT] + messages
    
    payload = {
        "model": "llama3",
        "stream": False,
        "messages": payload_messages
    }
    
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=60)
        response.raise_for_status()
        
        response_json = response.json()
        return response_json.get("message", {}).get("content", "")
    except requests.exceptions.RequestException as e:
        raise RuntimeError(f"Failed to communicate with Ollama: {e}")
